// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbbwguwzjjhuldmlrebh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiYndndXd6ampodWxkbWxyZWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTk4ODksImV4cCI6MjA2NTI5NTg4OX0.knk7Uaw91DArToECaNFBBiQQ5FsgXPbBEScudZa5las";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);